### PR TITLE
Added bitcoin-core 22.0

### PR DESCRIPTION
**Pull request by Silvenga**
Bitcoin Core changed how verification occurs.
- sigs are now detached from the hashes.
- multiple detached sigs are created against the hashes.

So my changes from previous versions:
- Added all maintainer pub keys.
- Added keys.openpgp.org as the second key server to attempt (one of the keys isn't on the standard key servers). keys.openpgp.org also returns junk for some of the other keys, so if ubuntu fails, use keys.openpgp.org. Not perfect but :shrug:

See https://github.com/bitcoin/bitcoin/issues/22982 for context.

### CODE REVIEW

**Comment by Silvenga** [comment]
It should be noted that while I can build correctly locally, I'm getting some oddities from

**Comment by schildbach** [comment]
But it doesn't run:

```
container_linux.go:380: starting container process caused: exec: "/entrypoint.sh": permission denied: unknown
```

I assume this is the entrypoint.sh script trying to assign permissions. Are the UID and GID of the `bitcoin` user different between Debian and Alpine versions? Sadly it doesn't print them, so I do not know how to chown my existing volume.

In this regard, I think it would be a good idea to merge #120, as it would give control about UID/GID to the system admin.

**Comment by Silvenga** [comment]
Ah, likely because I was testing my build on Windows. I'll fix that.

**Comment by Silvenga** [comment]
Fixed the execution bit.

**Comment by Zorato** [comment]
Hey, any updates on this one?

**Comment by ravz** [comment]
keen to see this merged please

**Comment by ruimarinho** [comment]
@ravz @Zorato I'll be merging this today. Tough week, sorry!

**Comment by ruimarinho** [comment]
Landed in https://github.com/ruimarinho/docker-bitcoin-core/commit/771d9b34afdb01bdc687a85ed95f425167262e42. Had to introduce a few tweaks on the build system as "22" is the new major version, as opposed to "0.22". For convenience, there is now a `ruimarinho/bitcoin-core:22` lineage for all `22.x` future releases.

Don't worry about the failed build marker next to the commit. Due to the recent expiration of Let's Encrypt Root CA, version 0.11 was not able to be compiled. I've updated the certs to make sure it's back to green.

Thanks for the great contribution @Silvenga. If you like and trust this image, make sure [you star it on Docker Hub](https://hub.docker.com/r/ruimarinho/bitcoin-core) to increase the likelihood of a best match.

**Comment by ruimarinho** [comment]
@schildbach custom uid/gid support is now available!

**Pull request closed without merging**
