### PR TITLE
update to version 0.21.0

### PR DESCRIPTION
**Pull request by aphex3k**

### CODE REVIEW

**Comment by aphex3k** [comment]
@ruimarinho It fails logging in docker hub...

**Comment by keblek** [comment]
does this expose the port for signet?

**Comment by aphex3k** [comment]
> does this expose the port for signet?

Not sure about signet, but you can see the exposed ports in the Dockerfile: `EXPOSE 8332 8333 18332 18333 18443 18444`

**Comment by keblek** [comment]
Default Bitcoin network protocol listen port is 38333 (instead of 8333)
Default RPC connection port is 38332 (instead of 8332)

https://en.bitcoin.it/wiki/Signet

add this to the readme as well?

**Comment by keblek** [comment]
% docker exec --user bitcoin kind_lehmann bitcoin-cli -signet getmininginfo
{
  "blocks": 24210,
  "difficulty": 0.002901660475040805,
  "networkhashps": 23188.24385728437,
  "pooledtx": 0,
  "chain": "signet",
  "warnings": ""
}

works for me

**Comment by ruimarinho** [comment]
Landed in https://github.com/ruimarinho/docker-bitcoin-core/commit/e1455ce7d6f9f2842061b980d9c516b9a6d19dae, thank you @aphex3k.

`EXPOSE` is purely cosmetic. You can map any port you want from the container.

**Pull request closed without merging**
